#!/usr/bin/env bash

# Strict settings
set -o errexit
set -o pipefail
set -o nounset

# Magic variables
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename "${__file}" .sh)"

# Print out usage information
usage() {
  cat <<HEREDOC
Usage:
  ${__base} [<arguments>]

Options:
  -h --help  Show this.
  -l --list  List notes.
  <name>     Create a note named <name>.md.
             You can also use slashes e.g. foo/bar to create foo/bar.md.
HEREDOC
}

# List all notes
list_notes() {
  # Get all Markdown files in $JOT_DIR
  shopt -s globstar nullglob
  for note in "${JOT_DIR}"/**/*.md; do
    # Strip the $JOT_DIR/ prefix
    note_path="${note#$JOT_DIR/}"
    # ... and the .md suffix
    echo -e "${note_path%.md}"
  done
}

# Make a new Markdown note
make_note() {
  # Check for note name
  if [[ -z "${*:-}" ]]; then
    note_dir="."
    # If not set, create one from today's date
    note_name="note-$(date +%Y-%m-%d)"
  else
    note_dir="$(dirname "${*}")"
    # Replace spaces with hyphens
    note_name="$(basename "${*// /-}")"
  fi

  # Check directory exists
  if [[ ! -d "${JOT_DIR}/${note_dir}" ]]; then
    # Create it if necessary
    mkdir -p "${JOT_DIR}/${note_dir}"
  fi

  # Make and open the note
  touch "${JOT_DIR}/${note_dir}/${note_name}.md"
  $EDITOR "${JOT_DIR}/${note_dir}/${note_name}.md"
}

# Drive it
main() {
  # Check if $JOT_DIR is set
  if [[ -z "${JOT_DIR:-}" ]]; then
    # If not, set to $HOME/Notes
    JOT_DIR="${HOME}/Notes"
  fi

  # Check directory exists
  if [[ ! -d "${JOT_DIR}" ]]; then
    # Create it if necessary
    mkdir -p "${JOT_DIR}"
  fi

  # Parse arguments
  if [[ "${1:-}" =~ ^-h|--help$ ]]; then
    usage
  elif [[ "${1:-}" =~ ^-l|--list$ ]]; then
    list_notes
  else
    # Pass in args as a string, not array
    make_note "${*:-}"
  fi
}

# Call it
main "${@:-}"
