#!/usr/bin/env bash

# Strict settings
set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# Magic variables
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
__root="$(cd "$(dirname "${__dir}")" && pwd)"

# Print out usage information
usage() {
  cat <<HEREDOC
    _       _
   (_) ___ | |_
   | |/ _ \| __|
   | | (_) | |_
  _/ |\___/ \__|
  |__/

Usage:
  ${__base} [<arguments>]

Options:
  -h --help  Show this screen.
  -l --list  List notes.
  <no flag>  Create a note.
HEREDOC
}

# List all notes
list_notes() {
  echo "Here's all your jots:"

  for note in "${JOT_PATH}"/*; do
    echo -e "\t$(basename ${note})"
  done
}

# Make a new Markdown note
make_note() {
  # Check for note name
  if [[ -z "${*:-}" ]]; then
    # If not set, create one from today's date
    note="note-$(date +%Y-%m-%d)"
  else
    # Replace spaces with hyphens
    note="${*// /-}"
  fi

  # Make and open the note
  touch "${JOT_PATH}/${note}.md"
  ${EDITOR} "${JOT_PATH}/${note}.md"
}

# Primary function
main() {
  # Check if $JOT_PATH is set
  if [[ -z "${JOT_PATH:-}" ]]; then
    # If not, set to $HOME/Notes
    JOT_PATH="${HOME}/Notes"

    # Check directory exists
    if [[ ! -d "${JOT_PATH}" ]]; then
      echo "Creating directory"
      # Create it if necessary
      mkdir -p "${JOT_PATH}"
    fi
  fi

  # Parse arguments
  if [[ "${1:-}" =~ ^-h|--help$ ]]; then
    usage
  elif [[ "${1:-}" =~ ^-l|--list$ ]]; then
    list_notes
  else
    # $* is a string, where $@ is an array
    ## Want a string to create the note
    make_note "${*:-}"
  fi
}

# Call the program
main "${@:-}"
